---------------------------------------------
-- Creación inicial del modelo
-- Crea tabla de clientes
-- wilmar.castano
---------------------------------------------

DROP TABLE IF EXISTS CLIENTES;

CREATE TABLE CLIENTES
(
	NM_ID INTEGER NOT NULL AUTO_INCREMENT COMMENT 'SECUENCIA PARA DIFERENCIAR LOS CLIENTES REGISTRADOS EN EL SISTEMA',
	DS_IDENTIFICACION VARCHAR(35) NOT NULL COMMENT 'NUMERO DE IDENTIFICACIÓN ',
	DS_NOMBRES VARCHAR(200) NOT NULL COMMENT 'NOMBRE COMPLETO DEL CLIENTE',
	DS_PRIMER_APELLIDO VARCHAR(200) NOT NULL COMMENT 'PRIMER APELLIDO DEL CLIENTE',
	DS_SEGUNDO_APELLIDO VARCHAR(200) COMMENT 'SEGUNDO APELLIDO DEL CLIENTE',
	DS_DIRECCION VARCHAR(255) NOT NULL COMMENT 'DIRECCION DE RESIDENCIA',
	DS_TELEFONO VARCHAR(20) COMMENT 'TELEFONO FIJO DEL CLIENTE',
	DS_CELULAR VARCHAR(20) NOT NULL COMMENT 'NUMERO DE TELEFONO MÓVIL DEL CLIENTE',
	DS_EMAIL VARCHAR(20) NOT NULL COMMENT 'CORREO ELECTRONICO DEL CLIENTE',
	DS_CIUDAD VARCHAR(20) NOT NULL COMMENT 'NOMBRE DE LA CIUDAD A LA QUE PERTENECE EL CLIENTE',
	FE_CREACION DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE CREACION DEL TENDERO EN EL SISTEMA',
	FE_MODIFICACION DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'FECHA DE LA ULTIMA ACTUALIZACION DEL REGISTRO',
	PRIMARY KEY (NM_ID),
	UNIQUE UQ_CLIENTES_DS_IDENTIFICACION(DS_IDENTIFICACION),
	INDEX IX_CLIENTES_DS_IDENTIFICACION (DS_IDENTIFICACION ASC)
)  COMMENT='TABLA DONDE SE ALMACENAN LOS DATOS BASICOS DE TODOS LOS CLIENTES RELACIONADOS CON LA APLICACION';